	/*-------------------------------------+
    | autogenerated by tb_gen.py on       |
    | Sun Dec 19 11:09:59 2021            |
    +-------------------------------------*/
test_no =                 1;
bits =                    16'b0011110001101101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110001101101;
#10;

test_no =                 2;
bits =                    16'b0100110110100100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000110110100100;
#10;

test_no =                 3;
bits =                    16'b0001101001101001;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001001101001;
#10;

test_no =                 4;
bits =                    16'b1011100010100001;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011101011111;
#10;

test_no =                 5;
bits =                    16'b0110010101100100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010101100100;
#10;

test_no =                 6;
bits =                    16'b0111101010010111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000011110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000010010111;
#10;

test_no =                 7;
bits =                    16'b0010011110101100;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011110101100;
#10;

test_no =                 8;
bits =                    16'b0001011100010000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011100010000;
#10;

test_no =                 9;
bits =                    16'b0001000100000111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000100000111;
#10;

test_no =                 10;
bits =                    16'b0000010100010010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000100010010;
#10;

test_no =                 11;
bits =                    16'b0110011011001110;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011011001110;
#10;

test_no =                 12;
bits =                    16'b1000110010100101;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001101011011;
#10;

test_no =                 13;
bits =                    16'b1110101011111111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010100000001;
#10;

test_no =                 14;
bits =                    16'b0100101000010100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101000010100;
#10;

test_no =                 15;
bits =                    16'b1100110011101010;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001100010110;
#10;

test_no =                 16;
bits =                    16'b1111110101110010;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        6;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000010001110;
#10;

test_no =                 17;
bits =                    16'b1100001111100001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110000011111;
#10;

test_no =                 18;
bits =                    16'b0000111100010000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001100010000;
#10;

test_no =                 19;
bits =                    16'b0011100011010000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000100011010000;
#10;

test_no =                 20;
bits =                    16'b1000010100110100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000011110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000011001100;
#10;

test_no =                 21;
bits =                    16'b1000100101100011;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001010011101;
#10;

test_no =                 22;
bits =                    16'b0101110000111001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110000111001;
#10;

test_no =                 23;
bits =                    16'b0100011011010100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011011010100;
#10;

test_no =                 24;
bits =                    16'b1100011110011101;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000100001100011;
#10;

test_no =                 25;
bits =                    16'b0010110000110011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000110000110011;
#10;

test_no =                 26;
bits =                    16'b1101001110101101;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000110001010011;
#10;

test_no =                 27;
bits =                    16'b0001101100101110;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001100101110;
#10;

test_no =                 28;
bits =                    16'b0100001100000000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001100000000;
#10;

test_no =                 29;
bits =                    16'b0011011011100010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011011100010;
#10;

test_no =                 30;
bits =                    16'b1111000101100101;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001010011011;
#10;

test_no =                 31;
bits =                    16'b1110110101101111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001010010001;
#10;

test_no =                 32;
bits =                    16'b0000011010010000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000010010000;
#10;

test_no =                 33;
bits =                    16'b1101010000110100;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101111001100;
#10;

test_no =                 34;
bits =                    16'b1010010000000100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000101111111100;
#10;

test_no =                 35;
bits =                    16'b1100111010000000;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000110000000;
#10;

test_no =                 36;
bits =                    16'b0100001010100000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001010100000;
#10;

test_no =                 37;
bits =                    16'b0100010110010001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010110010001;
#10;

test_no =                 38;
bits =                    16'b0011000110000100;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000110000100;
#10;

test_no =                 39;
bits =                    16'b0010101000110001;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101000110001;
#10;

test_no =                 40;
bits =                    16'b0100111101010010;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000111101010010;
#10;

test_no =                 41;
bits =                    16'b0100101000100101;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101000100101;
#10;

test_no =                 42;
bits =                    16'b1010000010000001;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000111101111111;
#10;

test_no =                 43;
bits =                    16'b1101111000001000;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000111111000;
#10;

test_no =                 44;
bits =                    16'b1011101101011101;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010010100011;
#10;

test_no =                 45;
bits =                    16'b1111010111111111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001000000001;
#10;

test_no =                 46;
bits =                    16'b1101101011001010;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010100110110;
#10;

test_no =                 47;
bits =                    16'b1101100100111001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011011000111;
#10;

test_no =                 48;
bits =                    16'b1110000101001011;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011010110101;
#10;

test_no =                 49;
bits =                    16'b0101111101010101;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000111101010101;
#10;

test_no =                 50;
bits =                    16'b0001011000110011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011000110011;
#10;

test_no =                 51;
bits =                    16'b1101100001000100;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011110111100;
#10;

test_no =                 52;
bits =                    16'b1001101100011001;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010011100111;
#10;

test_no =                 53;
bits =                    16'b0101011001100000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011001100000;
#10;

test_no =                 54;
bits =                    16'b1010101111110100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010000001100;
#10;

test_no =                 55;
bits =                    16'b0110001101001111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001101001111;
#10;

test_no =                 56;
bits =                    16'b1000000110000110;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        7;
regime_bits_expected =    16'b0000000001111110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000001111010;
#10;

test_no =                 57;
bits =                    16'b0011111110110110;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000111110110110;
#10;

test_no =                 58;
bits =                    16'b0010110110000011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000110110000011;
#10;

test_no =                 59;
bits =                    16'b0011111101010000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000111101010000;
#10;

test_no =                 60;
bits =                    16'b0111100100111101;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000011110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000100111101;
#10;

test_no =                 61;
bits =                    16'b0100011110101101;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011110101101;
#10;

test_no =                 62;
bits =                    16'b0001011011011111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011011011111;
#10;

test_no =                 63;
bits =                    16'b1111000111001111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001000110001;
#10;

test_no =                 64;
bits =                    16'b1110111101000001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000010111111;
#10;

test_no =                 65;
bits =                    16'b1101000101100000;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000111010100000;
#10;

test_no =                 66;
bits =                    16'b1101110110010000;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001001110000;
#10;

test_no =                 67;
bits =                    16'b1111000100110100;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001011001100;
#10;

test_no =                 68;
bits =                    16'b1000110000110010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001111001110;
#10;

test_no =                 69;
bits =                    16'b1101011100101000;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000100011011000;
#10;

test_no =                 70;
bits =                    16'b0100110011011100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000110011011100;
#10;

test_no =                 71;
bits =                    16'b0000000111011000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        7;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000001011000;
#10;

test_no =                 72;
bits =                    16'b1110100010101011;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011101010101;
#10;

test_no =                 73;
bits =                    16'b0100101010111100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101010111100;
#10;

test_no =                 74;
bits =                    16'b1001001010000110;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010101111010;
#10;

test_no =                 75;
bits =                    16'b1011010001110100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101110001100;
#10;

test_no =                 76;
bits =                    16'b1110000111011111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011000100001;
#10;

test_no =                 77;
bits =                    16'b0100111111001111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000111111001111;
#10;

test_no =                 78;
bits =                    16'b1101100100011001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011011100111;
#10;

test_no =                 79;
bits =                    16'b1100001111100100;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110000011100;
#10;

test_no =                 80;
bits =                    16'b1000001000100100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        6;
regime_bits_expected =    16'b0000000000111110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000011011100;
#10;

test_no =                 81;
bits =                    16'b0011000111110011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000111110011;
#10;

test_no =                 82;
bits =                    16'b0110100111111000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000111111000;
#10;

test_no =                 83;
bits =                    16'b0110110001111001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010001111001;
#10;

test_no =                 84;
bits =                    16'b1001100101010010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011010101110;
#10;

test_no =                 85;
bits =                    16'b0100100111000111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000100111000111;
#10;

test_no =                 86;
bits =                    16'b0110111001011000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011001011000;
#10;

test_no =                 87;
bits =                    16'b0111001110001101;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001110001101;
#10;

test_no =                 88;
bits =                    16'b0010100101001100;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000100101001100;
#10;

test_no =                 89;
bits =                    16'b0011101110110100;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000101110110100;
#10;

test_no =                 90;
bits =                    16'b0100111000011011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000111000011011;
#10;

test_no =                 91;
bits =                    16'b0100001001111000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001001111000;
#10;

test_no =                 92;
bits =                    16'b1101000000000110;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000111111111010;
#10;

test_no =                 93;
bits =                    16'b1100110000100001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001111011111;
#10;

test_no =                 94;
bits =                    16'b0000101100010001;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001100010001;
#10;

test_no =                 95;
bits =                    16'b0001010011000001;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010011000001;
#10;

test_no =                 96;
bits =                    16'b0000101111011011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001111011011;
#10;

test_no =                 97;
bits =                    16'b0111011001110001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001001110001;
#10;

test_no =                 98;
bits =                    16'b1010000001011000;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000111110101000;
#10;

test_no =                 99;
bits =                    16'b1111111101011010;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        8;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000000100110;
#10;

test_no =                 100;
bits =                    16'b0100011111001010;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011111001010;
#10;

test_no =                 101;
bits =                    16'b1000010011010100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000011110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000100101100;
#10;

test_no =                 102;
bits =                    16'b1000100011011100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001100100100;
#10;

test_no =                 103;
bits =                    16'b1010010111100011;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000101000011101;
#10;

test_no =                 104;
bits =                    16'b0111100010100011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000011110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000010100011;
#10;

test_no =                 105;
bits =                    16'b1011001101101100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000110010010100;
#10;

test_no =                 106;
bits =                    16'b0101011111000100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011111000100;
#10;

test_no =                 107;
bits =                    16'b0010010100100010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010100100010;
#10;

test_no =                 108;
bits =                    16'b1111111101001101;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        8;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000000110011;
#10;

test_no =                 109;
bits =                    16'b1010110001111100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001110000100;
#10;

test_no =                 110;
bits =                    16'b0011001000010001;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001000010001;
#10;

test_no =                 111;
bits =                    16'b0001000100000010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000100000010;
#10;

test_no =                 112;
bits =                    16'b0110100110101100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000110101100;
#10;

test_no =                 113;
bits =                    16'b1110100111011101;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011000100011;
#10;

test_no =                 114;
bits =                    16'b0011001111100010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001111100010;
#10;

test_no =                 115;
bits =                    16'b1010001010010000;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110101110000;
#10;

test_no =                 116;
bits =                    16'b1010000111110110;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000111000001010;
#10;

test_no =                 117;
bits =                    16'b0111000011101111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000011101111;
#10;

test_no =                 118;
bits =                    16'b0100011010111011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011010111011;
#10;

test_no =                 119;
bits =                    16'b0010111100000111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000111100000111;
#10;

test_no =                 120;
bits =                    16'b0101101100010111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000101100010111;
#10;

test_no =                 121;
bits =                    16'b0110111110011000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011110011000;
#10;

test_no =                 122;
bits =                    16'b1011111100110111;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000011001001;
#10;

test_no =                 123;
bits =                    16'b1001011010111001;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000101000111;
#10;

test_no =                 124;
bits =                    16'b0101001000010111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001000010111;
#10;

test_no =                 125;
bits =                    16'b1010001001101010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110110010110;
#10;

test_no =                 126;
bits =                    16'b1000111011111011;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000100000101;
#10;

test_no =                 127;
bits =                    16'b0011001011011110;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001011011110;
#10;

test_no =                 128;
bits =                    16'b1110011110000001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000001111111;
#10;

test_no =                 129;
bits =                    16'b0101001011010011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001011010011;
#10;

test_no =                 130;
bits =                    16'b0001100111011001;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000111011001;
#10;

test_no =                 131;
bits =                    16'b1101011011100100;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000100100011100;
#10;

test_no =                 132;
bits =                    16'b0000111111000101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001111000101;
#10;

test_no =                 133;
bits =                    16'b1011010101001010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101010110110;
#10;

test_no =                 134;
bits =                    16'b0011101010010111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000101010010111;
#10;

test_no =                 135;
bits =                    16'b0100011100001000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011100001000;
#10;

test_no =                 136;
bits =                    16'b1001010100001011;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001011110101;
#10;

test_no =                 137;
bits =                    16'b1001110110001100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001001110100;
#10;

test_no =                 138;
bits =                    16'b1101110010110010;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001101001110;
#10;

test_no =                 139;
bits =                    16'b0011110011000111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110011000111;
#10;

test_no =                 140;
bits =                    16'b0001111101000100;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011101000100;
#10;

test_no =                 141;
bits =                    16'b0101010011000000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010011000000;
#10;

test_no =                 142;
bits =                    16'b1110111101000000;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000011000000;
#10;

test_no =                 143;
bits =                    16'b0010110101110011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000110101110011;
#10;

test_no =                 144;
bits =                    16'b0100101001111010;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101001111010;
#10;

test_no =                 145;
bits =                    16'b0111010110000010;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000110000010;
#10;

test_no =                 146;
bits =                    16'b0000011010010010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000010010010;
#10;

test_no =                 147;
bits =                    16'b0000101011110101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001011110101;
#10;

test_no =                 148;
bits =                    16'b0101101101101001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000101101101001;
#10;

test_no =                 149;
bits =                    16'b1011001010000001;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000110101111111;
#10;

test_no =                 150;
bits =                    16'b0001010100100101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010100100101;
#10;

test_no =                 151;
bits =                    16'b1110010101011011;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001010100101;
#10;

test_no =                 152;
bits =                    16'b1111011011100111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000100011001;
#10;

test_no =                 153;
bits =                    16'b1111010001101001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001110010111;
#10;

test_no =                 154;
bits =                    16'b0100100100100010;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000100100100010;
#10;

test_no =                 155;
bits =                    16'b1011110000100000;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001111100000;
#10;

test_no =                 156;
bits =                    16'b1010110011011010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001100100110;
#10;

test_no =                 157;
bits =                    16'b1111010110111001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001001000111;
#10;

test_no =                 158;
bits =                    16'b0101001110111110;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001110111110;
#10;

test_no =                 159;
bits =                    16'b0000010010100111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000010100111;
#10;

test_no =                 160;
bits =                    16'b0101001010100011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001010100011;
#10;

test_no =                 161;
bits =                    16'b0100100111111011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000100111111011;
#10;

test_no =                 162;
bits =                    16'b0101001001011001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001001011001;
#10;

test_no =                 163;
bits =                    16'b1111011101001100;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000010110100;
#10;

test_no =                 164;
bits =                    16'b0010011100100101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011100100101;
#10;

test_no =                 165;
bits =                    16'b1100011001110110;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000100110001010;
#10;

test_no =                 166;
bits =                    16'b1010011011100100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000100100011100;
#10;

test_no =                 167;
bits =                    16'b0110100100010001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000100010001;
#10;

test_no =                 168;
bits =                    16'b1101110010000010;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001101111110;
#10;

test_no =                 169;
bits =                    16'b1111000101111100;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001010000100;
#10;

test_no =                 170;
bits =                    16'b1101111010010111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000101101001;
#10;

test_no =                 171;
bits =                    16'b1001111011011001;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000100100111;
#10;

test_no =                 172;
bits =                    16'b1010111000010111;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000111101001;
#10;

test_no =                 173;
bits =                    16'b1101000101100011;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000111010011101;
#10;

test_no =                 174;
bits =                    16'b0001001111100111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001111100111;
#10;

test_no =                 175;
bits =                    16'b0100101100011100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101100011100;
#10;

test_no =                 176;
bits =                    16'b1001111000100011;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000111011101;
#10;

test_no =                 177;
bits =                    16'b0011000100000000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000100000000;
#10;

test_no =                 178;
bits =                    16'b1110010011100010;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001100011110;
#10;

test_no =                 179;
bits =                    16'b0111000110110011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000110110011;
#10;

test_no =                 180;
bits =                    16'b0100101011000000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101011000000;
#10;

test_no =                 181;
bits =                    16'b0010001011101101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001011101101;
#10;

test_no =                 182;
bits =                    16'b0100000000000011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000000000011;
#10;

test_no =                 183;
bits =                    16'b0110000110110010;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000110110010;
#10;

test_no =                 184;
bits =                    16'b1001100101001011;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011010110101;
#10;

test_no =                 185;
bits =                    16'b1111011000111001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000111000111;
#10;

test_no =                 186;
bits =                    16'b0010100010101101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000100010101101;
#10;

test_no =                 187;
bits =                    16'b0101010011010000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010011010000;
#10;

test_no =                 188;
bits =                    16'b1001001010110110;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010101001010;
#10;

test_no =                 189;
bits =                    16'b0000001001100111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        6;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000001100111;
#10;

test_no =                 190;
bits =                    16'b0101110100000010;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110100000010;
#10;

test_no =                 191;
bits =                    16'b0000101101110111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001101110111;
#10;

test_no =                 192;
bits =                    16'b0111010001101100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000001101100;
#10;

test_no =                 193;
bits =                    16'b0010101101101000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101101101000;
#10;

test_no =                 194;
bits =                    16'b0101110101111101;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110101111101;
#10;

test_no =                 195;
bits =                    16'b1100100010100011;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011101011101;
#10;

test_no =                 196;
bits =                    16'b1100110111101001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001000010111;
#10;

test_no =                 197;
bits =                    16'b0101110011011011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110011011011;
#10;

test_no =                 198;
bits =                    16'b1111111101000111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        8;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000000111001;
#10;

test_no =                 199;
bits =                    16'b0100101001010011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101001010011;
#10;

test_no =                 200;
bits =                    16'b1001001001001010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010110110110;
#10;

test_no =                 201;
bits =                    16'b0001100011011011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000011011011;
#10;

test_no =                 202;
bits =                    16'b0111000001110111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000001110111;
#10;

test_no =                 203;
bits =                    16'b1111101101010011;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000010101101;
#10;

test_no =                 204;
bits =                    16'b0011010100001101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010100001101;
#10;

test_no =                 205;
bits =                    16'b0110110010001000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010010001000;
#10;

test_no =                 206;
bits =                    16'b1110101010100001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010101011111;
#10;

test_no =                 207;
bits =                    16'b0011010100111010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010100111010;
#10;

test_no =                 208;
bits =                    16'b0001110100010110;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010100010110;
#10;

test_no =                 209;
bits =                    16'b0000111100110000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001100110000;
#10;

test_no =                 210;
bits =                    16'b0000111111101100;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001111101100;
#10;

test_no =                 211;
bits =                    16'b0000111000100110;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001000100110;
#10;

test_no =                 212;
bits =                    16'b1011110010110011;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001101001101;
#10;

test_no =                 213;
bits =                    16'b0010101100101101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101100101101;
#10;

test_no =                 214;
bits =                    16'b1001100001110100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011110001100;
#10;

test_no =                 215;
bits =                    16'b1010110101000100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001010111100;
#10;

test_no =                 216;
bits =                    16'b1111100001111010;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000110000110;
#10;

test_no =                 217;
bits =                    16'b0010011001001110;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011001001110;
#10;

test_no =                 218;
bits =                    16'b1001101101000100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010010111100;
#10;

test_no =                 219;
bits =                    16'b0000101001110111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001001110111;
#10;

test_no =                 220;
bits =                    16'b1000101111010101;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000000101011;
#10;

test_no =                 221;
bits =                    16'b0111110110011100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        6;
regime_bits_expected =    16'b0000000000111110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000010011100;
#10;

test_no =                 222;
bits =                    16'b1001010100101001;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001011010111;
#10;

test_no =                 223;
bits =                    16'b0011111111000010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000111111000010;
#10;

test_no =                 224;
bits =                    16'b0101001001001001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001001001001;
#10;

test_no =                 225;
bits =                    16'b1111111101100101;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        8;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000000011011;
#10;

test_no =                 226;
bits =                    16'b0000100100011011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000100011011;
#10;

test_no =                 227;
bits =                    16'b0001111101001101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011101001101;
#10;

test_no =                 228;
bits =                    16'b1101010110111000;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101001001000;
#10;

test_no =                 229;
bits =                    16'b1000011101111100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000011110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000010000100;
#10;

test_no =                 230;
bits =                    16'b0100101011111011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101011111011;
#10;

test_no =                 231;
bits =                    16'b1100011000010111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000100111101001;
#10;

test_no =                 232;
bits =                    16'b1111111100110101;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        8;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000000001011;
#10;

test_no =                 233;
bits =                    16'b0110100011001001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000011001001;
#10;

test_no =                 234;
bits =                    16'b1010011011010000;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000100100110000;
#10;

test_no =                 235;
bits =                    16'b1111110011010111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        6;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000000101001;
#10;

test_no =                 236;
bits =                    16'b0011001101000100;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001101000100;
#10;

test_no =                 237;
bits =                    16'b0111101001001110;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000011110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000001001110;
#10;

test_no =                 238;
bits =                    16'b0011001110100111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001110100111;
#10;

test_no =                 239;
bits =                    16'b0011110111101010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000110111101010;
#10;

test_no =                 240;
bits =                    16'b0111000001010110;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000001010110;
#10;

test_no =                 241;
bits =                    16'b0110100100011110;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000100011110;
#10;

test_no =                 242;
bits =                    16'b0111110111101111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        6;
regime_bits_expected =    16'b0000000000111110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000011101111;
#10;

test_no =                 243;
bits =                    16'b0000100101110000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000101110000;
#10;

test_no =                 244;
bits =                    16'b0011100000010100;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000100000010100;
#10;

test_no =                 245;
bits =                    16'b0110101111010101;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001111010101;
#10;

test_no =                 246;
bits =                    16'b0111000110001001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000001110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000110001001;
#10;

test_no =                 247;
bits =                    16'b0011111110100011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000111110100011;
#10;

test_no =                 248;
bits =                    16'b1010010110111110;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000101001000010;
#10;

test_no =                 249;
bits =                    16'b1110001110101001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010001010111;
#10;

test_no =                 250;
bits =                    16'b0110110110000110;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010110000110;
#10;

test_no =                 251;
bits =                    16'b1101010010111111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101101000001;
#10;

test_no =                 252;
bits =                    16'b0011011100111001;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011100111001;
#10;

test_no =                 253;
bits =                    16'b0111111110100010;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        9;
regime_bits_expected =    16'b0000000111111110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000000000010;
#10;

test_no =                 254;
bits =                    16'b0011000000001101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000000001101;
#10;

test_no =                 255;
bits =                    16'b0000100000011010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000000011010;
#10;

test_no =                 256;
bits =                    16'b0000100101101100;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000101101100;
#10;

test_no =                 257;
bits =                    16'b0100000100011111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000100011111;
#10;

test_no =                 258;
bits =                    16'b0100000011011101;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000011011101;
#10;

test_no =                 259;
bits =                    16'b0011111000001101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000111000001101;
#10;

test_no =                 260;
bits =                    16'b1000011010010010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        5;
regime_bits_expected =    16'b0000000000011110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000101101110;
#10;

test_no =                 261;
bits =                    16'b0011010101000011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010101000011;
#10;

test_no =                 262;
bits =                    16'b1100010110110110;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000101001001010;
#10;

test_no =                 263;
bits =                    16'b0011101101000001;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000101101000001;
#10;

test_no =                 264;
bits =                    16'b0110101011001001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001011001001;
#10;

test_no =                 265;
bits =                    16'b1101111010100101;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000101011011;
#10;

test_no =                 266;
bits =                    16'b0100001011111101;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001011111101;
#10;

test_no =                 267;
bits =                    16'b0010010001000110;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000010001000110;
#10;

test_no =                 268;
bits =                    16'b0101001100110100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001100110100;
#10;

test_no =                 269;
bits =                    16'b0000110100100000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000100100000;
#10;

test_no =                 270;
bits =                    16'b1110010000011010;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001111100110;
#10;

test_no =                 271;
bits =                    16'b1110110110010011;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001001101101;
#10;

test_no =                 272;
bits =                    16'b0101000010000100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000010000100;
#10;

test_no =                 273;
bits =                    16'b1001000010111010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011101000110;
#10;

test_no =                 274;
bits =                    16'b0001110111101010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010111101010;
#10;

test_no =                 275;
bits =                    16'b1111110110010110;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        6;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000001101010;
#10;

test_no =                 276;
bits =                    16'b1001000111011000;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011000101000;
#10;

test_no =                 277;
bits =                    16'b0110011100101000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011100101000;
#10;

test_no =                 278;
bits =                    16'b1111011001110111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000110001001;
#10;

test_no =                 279;
bits =                    16'b1110011010100100;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000101011100;
#10;

test_no =                 280;
bits =                    16'b1010011100101000;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000100011011000;
#10;

test_no =                 281;
bits =                    16'b1010011101101010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000100010010110;
#10;

test_no =                 282;
bits =                    16'b1101111011110011;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000100001101;
#10;

test_no =                 283;
bits =                    16'b1100101001110101;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010110001011;
#10;

test_no =                 284;
bits =                    16'b1011011110100100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000100001011100;
#10;

test_no =                 285;
bits =                    16'b1011111010100110;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000101011010;
#10;

test_no =                 286;
bits =                    16'b0000101001011110;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001001011110;
#10;

test_no =                 287;
bits =                    16'b0111111010001001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        7;
regime_bits_expected =    16'b0000000001111110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000000001001;
#10;

test_no =                 288;
bits =                    16'b0110001100110001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001100110001;
#10;

test_no =                 289;
bits =                    16'b0001011111001000;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000011111001000;
#10;

test_no =                 290;
bits =                    16'b0110111000011011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011000011011;
#10;

test_no =                 291;
bits =                    16'b0011010111111110;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010111111110;
#10;

test_no =                 292;
bits =                    16'b1110111000001111;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000111110001;
#10;

test_no =                 293;
bits =                    16'b1101111110110001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000000001001111;
#10;

test_no =                 294;
bits =                    16'b1001001010000010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000110;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000010101111110;
#10;

test_no =                 295;
bits =                    16'b1110011001010110;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000000110101010;
#10;

test_no =                 296;
bits =                    16'b1111000110110011;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000001001001101;
#10;

test_no =                 297;
bits =                    16'b1110110010110001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000001101001111;
#10;

test_no =                 298;
bits =                    16'b0010101001011011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000001;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101001011011;
#10;

test_no =                 299;
bits =                    16'b0101011000101010;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000001;
mant_expected =           16'b0000011000101010;
#10;

test_no =                 300;
bits =                    16'b0100101111010100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    16'b0000000000000010;
exp_expected =            16'b0000000000000000;
mant_expected =           16'b0000101111010100;
#10;

