	/*-------------------------------------+
    | autogenerated by tb_gen.py on       |
    | Sun Dec 19 11:45:02 2021            |
    +-------------------------------------*/
test_no =                 1;
bits =                    5'b00111;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00001;
mant_expected =           5'b00001;
#10;

test_no =                 2;
bits =                    5'b01001;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    5'b00010;
exp_expected =            5'b00000;
mant_expected =           5'b00001;
#10;

test_no =                 3;
bits =                    5'b00011;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00001;
mant_expected =           5'b00000;
#10;

test_no =                 4;
bits =                    5'b10111;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    5'b00010;
exp_expected =            5'b00000;
mant_expected =           5'b00001;
#10;

test_no =                 5;
bits =                    5'b01100;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    5'b00110;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 6;
bits =                    5'b01111;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        5;
regime_bits_expected =    5'b11110;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 7;
bits =                    5'b00100;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 8;
bits =                    5'b00010;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 9;
bits =                    5'b11011;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00000;
mant_expected =           5'b00001;
#10;

test_no =                 10;
bits =                    5'b00000;
sign_expected =           0;
reg_s_expected =          'bx;
reg_len_expected =        'bx;
regime_bits_expected =    5'b00000;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 11;
bits =                    5'b11010;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00001;
mant_expected =           5'b00000;
#10;

test_no =                 12;
bits =                    5'b10001;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        5;
regime_bits_expected =    5'b11110;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 13;
bits =                    5'b11101;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00001;
mant_expected =           5'b00000;
#10;

test_no =                 14;
bits =                    5'b00001;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        4;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 15;
bits =                    5'b11110;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        3;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 16;
bits =                    5'b01011;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    5'b00010;
exp_expected =            5'b00001;
mant_expected =           5'b00001;
#10;

test_no =                 17;
bits =                    5'b11000;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    5'b00010;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 18;
bits =                    5'b10100;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    5'b00110;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 19;
bits =                    5'b10110;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    5'b00010;
exp_expected =            5'b00001;
mant_expected =           5'b00000;
#10;

test_no =                 20;
bits =                    5'b10011;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    5'b00110;
exp_expected =            5'b00001;
mant_expected =           5'b00000;
#10;

test_no =                 21;
bits =                    5'b01110;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    5'b01110;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 22;
bits =                    5'b11100;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 23;
bits =                    5'b10101;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    5'b00010;
exp_expected =            5'b00001;
mant_expected =           5'b00001;
#10;

test_no =                 24;
bits =                    5'b01010;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    5'b00010;
exp_expected =            5'b00001;
mant_expected =           5'b00000;
#10;

test_no =                 25;
bits =                    5'b00110;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00001;
mant_expected =           5'b00000;
#10;

test_no =                 26;
bits =                    5'b01101;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        3;
regime_bits_expected =    5'b00110;
exp_expected =            5'b00001;
mant_expected =           5'b00000;
#10;

test_no =                 27;
bits =                    5'b11001;
sign_expected =           1;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00001;
mant_expected =           5'b00001;
#10;

test_no =                 28;
bits =                    5'b10000;
sign_expected =           1;
reg_s_expected =          'bx;
reg_len_expected =        'bx;
regime_bits_expected =    5'b00000;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 29;
bits =                    5'b10010;
sign_expected =           1;
reg_s_expected =          1;
reg_len_expected =        4;
regime_bits_expected =    5'b01110;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

test_no =                 30;
bits =                    5'b00101;
sign_expected =           0;
reg_s_expected =          0;
reg_len_expected =        2;
regime_bits_expected =    5'b00001;
exp_expected =            5'b00000;
mant_expected =           5'b00001;
#10;

test_no =                 31;
bits =                    5'b01000;
sign_expected =           0;
reg_s_expected =          1;
reg_len_expected =        2;
regime_bits_expected =    5'b00010;
exp_expected =            5'b00000;
mant_expected =           5'b00000;
#10;

